### PR TITLE
Adding image upload for user model

### PR DESCRIPTION
**Pull request by josephburgess**
included tests for image uploads in the controller and model specs. All tests passing on the backend on my machine (proof below because I wonder if that will be the same for everyone!!!)

image

### CODE REVIEW

**Review by ShaunFlood — COMMENTED** [review]
Test are passing and no conflicts.

**Review by ShaunFlood — APPROVED** [review]

**Comment by MillieKS** [comment]
Approved with Shaun

**Review by MillieKS — APPROVED** [review]
checked with Shaun looks good

**Review by MillieKS — APPROVED** [review]
checked with Shaun looks good

**Review by MillieKS — APPROVED** [review]
checked with Shaun looks good

**Review by tomrolfe20 — APPROVED** [review]

**Comment by tomrolfe20** [comment]
Approving due to user approval issues

**Pull request merged**
